// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMJX8WHNYO41TqvnRbGWVEfwjKCsOnf3I',
    appId: '1:275639556970:web:f9120fc24061eebd9ba313',
    messagingSenderId: '275639556970',
    projectId: 'chatapp-2e73d',
    authDomain: 'chatapp-2e73d.firebaseapp.com',
    storageBucket: 'chatapp-2e73d.firebasestorage.app',
    measurementId: 'G-WTJ2E29SC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcdQGnyKZQWvcQWbr1IKjXlpDyhjhufYU',
    appId: '1:275639556970:android:e88bb33a4e8f865c9ba313',
    messagingSenderId: '275639556970',
    projectId: 'chatapp-2e73d',
    storageBucket: 'chatapp-2e73d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwt14a6No0hnI0rqp5jeDgFDi3dywmGtY',
    appId: '1:275639556970:ios:4e0dc877322a53519ba313',
    messagingSenderId: '275639556970',
    projectId: 'chatapp-2e73d',
    storageBucket: 'chatapp-2e73d.firebasestorage.app',
    iosBundleId: 'com.example.sabak23ChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwt14a6No0hnI0rqp5jeDgFDi3dywmGtY',
    appId: '1:275639556970:ios:4e0dc877322a53519ba313',
    messagingSenderId: '275639556970',
    projectId: 'chatapp-2e73d',
    storageBucket: 'chatapp-2e73d.firebasestorage.app',
    iosBundleId: 'com.example.sabak23ChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMJX8WHNYO41TqvnRbGWVEfwjKCsOnf3I',
    appId: '1:275639556970:web:e91659971275909f9ba313',
    messagingSenderId: '275639556970',
    projectId: 'chatapp-2e73d',
    authDomain: 'chatapp-2e73d.firebaseapp.com',
    storageBucket: 'chatapp-2e73d.firebasestorage.app',
    measurementId: 'G-7EBGDK8YBS',
  );
}
